# .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/RxDBDotNet"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    reviewers:
      - "rbeauchamp"
    assignees:
      - "rbeauchamp"
