# .github/release-drafter.yml
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
  - title: '🧹 Chores'
    labels:
      - 'chore'
  - title: '📚 Documentation'
    labels:
      - 'docs'
  - title: '💅 Styles'
    labels:
      - 'style'
  - title: '♻️ Refactoring'
    labels:
      - 'refactor'
  - title: '⚡️ Performance'
    labels:
      - 'perf'
  - title: '🧪 Tests'
    labels:
      - 'test'
  - title: '🏗️ Build'
    labels:
      - 'build'
  - title: '🔄 CI'
    labels:
      - 'ci'
  - title: '↩️ Revert'
    labels:
      - 'revert'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's Changed

  $CHANGES
autolabeler:
  - label: 'feat'
    title:
      - '/^feat(\([^)]+\))?:/i'
  - label: 'fix'
    title:
      - '/^fix(\([^)]+\))?:/i'
  - label: 'chore'
    title:
      - '/^chore(\([^)]+\))?:/i'
  - label: 'docs'
    title:
      - '/^docs(\([^)]+\))?:/i'
  - label: 'style'
    title:
      - '/^style(\([^)]+\))?:/i'
  - label: 'refactor'
    title:
      - '/^refactor(\([^)]+\))?:/i'
  - label: 'perf'
    title:
      - '/^perf(\([^)]+\))?:/i'
  - label: 'test'
    title:
      - '/^test(\([^)]+\))?:/i'
  - label: 'build'
    title:
      - '/^build(\([^)]+\))?:/i'
  - label: 'ci'
    title:
      - '/^ci(\([^)]+\))?:/i'
  - label: 'revert'
    title:
      - '/^revert(\([^)]+\))?:/i'